GET http://localhost:5196/game

###
GET http://localhost:5196/games/get/1

###
POST http://localhost:5196/games/add
Content-Type: application/json

{
    "Name": "Metro Exodus",
    "Genre": "Horror Shooting",
    "Price": 769
}

###
PUT http://localhost:5196/games/update/2
Content-Type: application/json

{
    "Name": "Not Assassin's Creed",
    "Genre": "IDK",
    "Price": 10000
}

###
DELETE http://localhost:5196/games/delete/1